### ISSUE TITLE
Git clone command is for wrong repo

### ISSUE THREAD

**Issue by skotzko** [first20hours/keyzen-colemak#1]
In the README, the instructions for cloning and running Keyzen-Colemak locally point to the wrong Github repo.

Currently, the instruction is to run `git clone git@github.com:eurekaoverdrive/keyzen-colemak.git`. This will produce an error. 

Instead, it should be: `git clone https://github.com/first20hours/keyzen-colemak.git`

**Comment by first20hours** [comment]
Fixed
