### ISSUE TITLE
Saving progress?

### ISSUE THREAD

**Issue by stevenqzhang** [first20hours/keyzen-colemak#7]
Does this save process? Or is the idea to run it in the background and never shut it down?

**Comment by mcavallo** [comment]
Well, it uses local storage so you can potentially dump it and re-create it somewhere else if you want

**Comment by ranelpadon** [comment]
For those interested, I was inspired by his book and journey of learning Colemak. So, I forked a version of it here, and added features/improvements:

**KeyZen-Colemak-DH**
https://ranelpadon.github.io/keyzen-colemak-dh/

Features:
- Keyboard layout could be chosen. Colemak DH (angle mod) is the default/recommended.
- Keyboard layout images are displayed depending on your layout as a handy reference.
- Character sequences are spitted gradually and randomly, starting with the most important ones.
- If you commit mistakes, the letters will be reintroduced again to maximize training.
- Intensity/rigor could be adjusted.
- Speed/accuracy stats are displayed.
- Characters could be reset/skipped by clicking on it.
- There's a timer to keep track your progress, or for better planning.
- Useful for beginners to familiarize the keys.
- Useful for experienced users to strengthen their weaknesses (e.g. specific letters, capital letters, punctuation, etc).

More details:
https://github.com/ranelpadon/keyzen-colemak-dh/blob/master/README.md
